import type {
  AgentId,
  ArchitectureResult,
  DiffLine,
} from '@shared/types'

const MOCK_DIAGRAM = `<svg width="800" height="400" viewBox="0 0 800 400" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="800" height="400" fill="#0D0D0D" rx="12"/>
  <rect x="50" y="60" width="160" height="80" rx="8" fill="#1A1A1A" stroke="#FF6B00" stroke-width="2"/>
  <text x="130" y="108" text-anchor="middle" fill="#FF6B00" font-family="monospace" font-size="13">API Gateway</text>
  <rect x="320" y="60" width="160" height="80" rx="8" fill="#1A1A1A" stroke="#CCFF00" stroke-width="2"/>
  <text x="400" y="108" text-anchor="middle" fill="#CCFF00" font-family="monospace" font-size="13">Orchestrator</text>
  <rect x="590" y="60" width="160" height="80" rx="8" fill="#1A1A1A" stroke="#33FF77" stroke-width="2"/>
  <text x="670" y="108" text-anchor="middle" fill="#33FF77" font-family="monospace" font-size="13">Cache Layer</text>
  <rect x="50" y="220" width="160" height="80" rx="8" fill="#1A1A1A" stroke="#FF6B00" stroke-width="2"/>
  <text x="130" y="268" text-anchor="middle" fill="#FF6B00" font-family="monospace" font-size="13">Microservice A</text>
  <rect x="320" y="220" width="160" height="80" rx="8" fill="#1A1A1A" stroke="#FF6B00" stroke-width="2"/>
  <text x="400" y="268" text-anchor="middle" fill="#FF6B00" font-family="monospace" font-size="13">Microservice B</text>
  <rect x="590" y="220" width="160" height="80" rx="8" fill="#1A1A1A" stroke="#FF6B00" stroke-width="2"/>
  <text x="670" y="268" text-anchor="middle" fill="#FF6B00" font-family="monospace" font-size="13">Database</text>
  <line x1="210" y1="100" x2="320" y2="100" stroke="#1A1A1A" stroke-width="2"/>
  <line x1="480" y1="100" x2="590" y2="100" stroke="#1A1A1A" stroke-width="2"/>
  <line x1="130" y1="140" x2="130" y2="220" stroke="#1A1A1A" stroke-width="2"/>
  <line x1="400" y1="140" x2="400" y2="220" stroke="#1A1A1A" stroke-width="2"/>
  <line x1="670" y1="140" x2="670" y2="220" stroke="#1A1A1A" stroke-width="2"/>
  <line x1="210" y1="260" x2="320" y2="260" stroke="#1A1A1A" stroke-width="2"/>
  <line x1="480" y1="260" x2="590" y2="260" stroke="#1A1A1A" stroke-width="2"/>
</svg>`

const MOCK_CODE = `// Architecture generated by Cerebras Nexus
// Agents: search → layout → codeXml → shield → optimize → security → docs → verify

const apiGateway = new Gateway({
  port: 8080,
  middleware: [rateLimit, auth, cors],
})

const orchestrator = new Orchestrator({
  services: [microserviceA, microserviceB],
  strategy: 'circuit-breaker',
})

const cache = new CacheLayer({
  provider: 'redis',
  ttl: 3600,
})

const db = new Database({
  type: 'postgresql',
  replica: 2,
})`

const MOCK_DIFF: DiffLine[] = [
  { type: 'unchanged', content: '// Cerebras Nexus Architecture', lineNumber: 1 },
  { type: 'added', content: '+ const apiGateway = new Gateway({ port: 8080 })', lineNumber: 2 },
  { type: 'unchanged', content: '// previous: Express app', lineNumber: 3 },
  { type: 'removed', content: '- const app = express()', lineNumber: 4 },
  { type: 'added', content: '+ const orchestrator = new Orchestrator({', lineNumber: 5 },
  { type: 'added', content: '+   services: [microserviceA, microserviceB]', lineNumber: 6 },
  { type: 'added', content: '+ })', lineNumber: 7 },
  { type: 'unchanged', content: 'const cache = new CacheLayer({ provider: "redis" })', lineNumber: 8 },
  { type: 'removed', content: '- // TODO: add caching', lineNumber: 9 },
]

const AGENT_ORDER: AgentId[] = [
  'search',
  'layout',
  'codeXml',
  'shieldCheck',
  'zap',
  'lock',
  'fileText',
  'clipboardCheck',
]

export function runMockPipeline(
  input: string,
  onProgress: (agentId: AgentId, progress: number, status: string) => void,
): Promise<ArchitectureResult> {
  return new Promise((resolve) => {
    let step = 0

    const tick = () => {
      if (step >= AGENT_ORDER.length) {
        resolve({
          diagramSvg: MOCK_DIAGRAM,
          code: MOCK_CODE,
          diffLines: MOCK_DIFF,
          compliance: { gdpr: true, details: ['Data encryption at rest', 'Access logging enabled'] },
          security: { passed: 12, failed: 0, warnings: ['Review CORS policy'] },
          validation: { valid: true, errors: [] },
        })
        return
      }

      const agentId = AGENT_ORDER[step]
      onProgress(agentId, 0, 'working')

      let pct = 0
      const interval = setInterval(() => {
        pct += 8
        if (pct >= 100) {
          clearInterval(interval)
          onProgress(agentId, 100, 'done')
          step++
          setTimeout(tick, 200)
        } else {
          onProgress(agentId, pct, 'working')
        }
      }, 100)
    }

    setTimeout(tick, 500)
  })
}
